import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import Sidebar from '../components/Sidebar';
import Header from '../components/Header';
import './globals.css';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Data dashboad',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} min-h-screen bg-background`}>
        <div className="flex min-h-screen">
          <Sidebar />

          <div className="flex-1 flex flex-col">
            <Header />

            <main className="flex-1 p-4 bg-white overflow-y-auto max-w-screen">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
